version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_clientes_pedidos
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: clientes_pedidos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
